#pragma once
// NOLINTBEGIN(readability-identifier-naming)

#include <functional>
#include <string>
#include <string_view>
#include <vector>

#include <llama.h>
#include <picojson/picojson.h>

#include "LlamaFinetuningHelpers.hpp"
#include "LlmContext.hpp"
#include "common/chat.h"
#include "qvac-lib-inference-addon-cpp/BlobsStream.hpp"
#include "qvac-lib-inference-addon-cpp/GGUFShards.hpp"
#include "qvac-lib-inference-addon-cpp/InitLoader.hpp"
#include "qvac-lib-inference-addon-cpp/Logger.hpp"
#include "qvac-lib-inference-addon-cpp/RuntimeStats.hpp"

class LlamaModel {
public:
  LlamaModel(const LlamaModel&) = delete;
  LlamaModel& operator=(const LlamaModel&) = delete;
  LlamaModel(LlamaModel&&) = delete;
  LlamaModel& operator=(LlamaModel&&) = delete;
  using Input = std::variant<std::string, std::vector<uint8_t>>;
  using InputView = Input;
  using Output = std::string;

  /**
   * The Constructor for llama model.
   * @param model_path - path to the model file.
   * @param projectorPath - path to the projector file.
   * @param configFilemap - map of configuration files.
   */
  LlamaModel(
      // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
      const std::string& modelPath, const std::string& projectionPath,
      std::unordered_map<std::string, std::string>& configFilemap);

  /**
   * The Destructor for llama model.
   */
  ~LlamaModel();

  /// @brief Call for asynchronous loading of file shards.
  void set_weights_for_file(
      const std::string& filename,
      std::unique_ptr<std::basic_streambuf<char>>&& shard);

  /**
   * The stop method. It stops the model inference.
   */
  void stop();

  /**
   * The process method. It reserves in input string and generated a reply.
   *
   * @param input - user request from the model in natural language.
   * @param output_callback - callback function that will be called for each
   * token generated by the model. The callback receives the decoded text for
   * the token as a string parameter. If nullptr, no streaming callback will
   * occur.
   *
   * @return a replay from the model
   */
  Output process(
      const Input& input,
      const std::function<void(const Output&)>& outputCallback = {});

  /**
   * The Reset method.
   */
  void reset() {}

  /**
   * Initialize backend (llama.cpp setup).
   */
  void initializeBackend();

    /**
     * Check if model is loaded.
     */
    bool isLoaded();

    /**
     * Ensure model is initialized
     */
    inline void waitForLoadInitialization() {
      initLoader.waitForLoadInitialization();
    }

        /**
         * Access the underlying llama context pointer.
         */
        llama_context* getContext();

        /**
         * Access the underlying llama model pointer.
         */
        llama_model* getModel();

        /**
         * Access the mutable common parameters associated with the active context.
         */
        common_params& getCommonParams();

    /**
     * The Runtime stats method. It outputs the runtime infernce stats per job.
     *
     * @return inference stats.
     */
    qvac_lib_inference_addon_cpp::RuntimeStats runtimeStats();

    /**
     * Static callback function for llama.cpp logging
     */
    static void
    llamaLogCallback(ggml_log_level level, const char* text, void* user_data);

    /**
     * Finetune the model using LoRA.
     *
     * @param params - finetuning parameters
     * @param logCallback - callback function for logging messages
     */
    void finetune(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params,
        std::function<void(const std::string&)> logCallback = {},
        bool allowResumeFromPause = false);

    /**
     * Request pause of finetuning (sets pause flag in checkpoint state).
     * Returns true if pause was requested, false if not finetuning.
     */
    bool requestPause();

    /**
     * Clear pause request flag (for resume).
     */
    void clearPauseRequest();

  private:
    /**
     * The Common params parse method. It parses the common params.
     *
     * @param model_path - model path.
     * @param configFilemap - config file map.
     * @param params - common params.
     */
    void CommonParamsParse(
        const std::string& modelPath,
        std::unordered_map<std::string, std::string>& configFilemap,
        common_params& params);

    /**
     * The Format prompt method. It formats the prompt json to chat messages.
     *
     * @param input - input prompt.
     * @return formatted chat messages and tools.
     */
    std::pair<std::vector<common_chat_msg>, std::vector<common_chat_tool>>
    FormatPrompt(const std::string& input);

    /**
     * The Handle cache method. It handles the cache of the chat session.
     *
     * @param chatMsgs - chat messages.
     * @param tools - tools.
     * @param inputPrompt - input prompt.
     * @return true if the cache is loaded, false otherwise.
     */
    bool HandleCache(
        std::vector<common_chat_msg>& chatMsgs,
        std::vector<common_chat_tool>& tools, const std::string& inputPrompt);

    /**
     * The Load cache method. It loads the cache of the chat session.
     *
     * @param embd_inp - input tokens.
     */
    bool LoadCache();

    /**
     * The Save cache method. It saves the cache of the chat session.
     *
     */
    void SaveCache();

    /**
     * The Reset state method. It resets the model state.
     */
    void ResetState(bool resetStats = true);

    /**
     * Create the appropriate context based on model type and projector path
     * @param model_path - path to the model file
     * @param params - common parameters
     * @param common_init_result - Result of loading/initializing model from
     * .gguf file(s)
     * @return unique_ptr to the appropriate LlmContext
     */
    std::unique_ptr<LlmContext> CreateContext(
        const std::string& projectionPath, common_params& params,
        common_init_result&& llamaInit);

    /**
     * The Load media method. It loads the media.
     *
     * @param input - input.
     * @return true if the media is loaded, false otherwise.
     */
    bool LoadMedia(const Input& input);

    void init(
        const std::string& modelPath, const std::string& projectionPath,
        std::unordered_map<std::string, std::string>& configFilemap);

    // Finetuning private methods
    void validateFinetuningParams(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params);
    ggml_opt_dataset_t prepareTrainingDataset(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params);
    void initializeLoraAdapter(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params,
        uint32_t targetModules, llama_adapter_lora*& adapter);
    llama_finetuning_helpers::LoraLrSchedulerState createLrScheduler(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params,
        int64_t totalSteps);
    std::unique_ptr<llama_finetuning_helpers::TrainingCheckpointState>
    initializeCheckpointing(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params,
        llama_adapter_lora* adapter,
        llama_finetuning_helpers::LoraLrSchedulerState* scheduler,
        std::function<void(const std::string&)> logFn);
    void configureOptimizer(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params,
        llama_adapter_lora* adapter,
        llama_finetuning_helpers::LoraLrSchedulerState& scheduler,
        llama_finetuning_helpers::TrainingCheckpointState* checkpointState,
        bool loadOptimizerState = false);
    void executeTrainingLoop(
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params,
        ggml_opt_dataset_t dataset, int64_t trainSplit,
        llama_finetuning_helpers::LoraLrSchedulerState& scheduler,
        llama_finetuning_helpers::TrainingCheckpointState* checkpointState,
        std::function<void(const std::string&)> logCallback,
        uint32_t startEpoch = 0, bool resumingFromPause = false);
    void saveLoraAdapter(
        llama_adapter_lora* adapter,
        const qvac_lib_inference_addon_cpp::FinetuningParameters& params);

    // private members
    std::string _sessionPath;
    bool _cache_disabled = true;

    // Store the appropriate context (TextLlmContext or MtmdLlmContext)
    std::unique_ptr<LlmContext> llmContext;

    const std::string loading_context;
    const GGUFShards _shards;
    friend class InitLoader;
    InitLoader initLoader;

    bool isTextLlm = false;
    bool backendInitialized = false;
    bool isStreaming = false;
    std::map<std::string, std::unique_ptr<std::basic_streambuf<char>>>
        singleGgufStreamedFiles;

    // configuration values parsed from configFilemap
    llama_pos configured_n_discarded = 0;

    // Finetuning state
    llama_finetuning_helpers::TrainingCheckpointState* currentCheckpointState_ =
        nullptr;
    bool optimizerInitialized_ =
        false; // Track if optimizer has been initialized for this context
};

// NOLINTEND(readability-identifier-naming)
