name: Delete NPM Versions (LLM)

on:
  pull_request:
    types:
      - closed
    paths:
      - "packages/qvac-lib-infer-llamacpp-llm/**"
  workflow_dispatch:
    inputs:
      version:
        description: "Specific version to target for deletion"
        required: false
        type: string
      pr-number:
        description: "PR number to target for deletion"
        required: false
        type: string
      pattern:
        description: "Pattern to target for deletion"
        required: false
        type: string
      packages:
        description: "Packages to target for deletion, space separated"
        required: false
        type: string
        default: "@qvac/llm-llamacpp @tetherto/llm-llamacpp"
      dry-run:
        description: "Is dry run? If true, lists versions without deleting."
        type: boolean
        default: true

run-name: Delete NPM Versions (llm-llamacpp) ${{ inputs.version }} ${{ inputs.pr-number }} ${{ inputs.dry-run }}

permissions:
  contents: read
  
jobs:
  on-pr-close:
    uses: ./.github/workflows/_reusable-on-pr-close-addon.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      pr-number: ${{ inputs.pr-number }}
      pattern: ${{ inputs.pattern }}
      packages: ${{ inputs.packages }}
      dry-run: ${{ inputs.dry-run || true }}
