name: On PR Trigger (LLM)

on:
  push:
    branches:
      - tmp-test-workflow-invoke   

jobs:
  cpp-lint:
    uses: tetherto/qvac-devops/.github/workflows/cpp-lint.yaml@tmp-fix-release-env
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with:
      sha: ${{ github.event.pull_request.base.sha }}
      pr_head_sha: ${{ github.event.pull_request.head.sha }}
      workdir: packages/qvac-lib-infer-llamacpp-llm
